"""fix organization_activity primary key

Revision ID: f501911fd08b
Revises: c2e05c19f44a
Create Date: 2026-02-20 16:45:06.392327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f501911fd08b'
down_revision: Union[str, Sequence[str], None] = 'c2e05c19f44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_index(op.f('ix_building_geo_geog'), table_name='building', postgresql_using='gist')
    op.create_unique_constraint("uq_organization_activity_org_activity", 'organization_activity', ['organization_id', 'activity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_organization_activity_org_activity", 'organization_activity', type_='unique')
    # op.create_index(op.f('ix_building_geo_geog'), 'building', [sa.literal_column('geography(st_setsrid(st_makepoint(longitude, latitude), 4326))')], unique=False, postgresql_using='gist')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    # ### end Alembic commands ###
