groups:
  - name: organizations
    rules:
      - alert: OrganizationsApiDown
        expr: up{job="organizations-app"} == 0
        for: 1m
        labels: 
          severity: critical
        annotations:
          summary: "organizations-app недоступен"
          description: "Prometheus не может собрать метрики с app:8000 уже 1 минуту"

      - alert: OrganizationsApiHigh5xxRate
        expr: sum(rate(http_requests_total{job="organizations-app", status=~"5.."}[5m])) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "organizations-app возвращает 5xx"
          description: "За последние 5 минут сервис начал отдавать ответы 5xx"

      - alert: OrganizationsApiHighLatencyP95
        expr: >
          histogram_quantile(
            0.95,
            sum(rate(http_request_duration_seconds_bucket{job="organizations-app"}[5m])) by (le)
          ) > 0.5
          and
          sum(increase(http_requests_total{job="organizations-app"}[5m])) >= 10
        for: 30s # 5m можно заменить на 30s для более быстрой реакции на проблему
        labels:
          severity: warning
        annotations:
          summary: "organizations-app отвечает медленно"
          description: "p95 latency выше 500ms за последние 5 минут при трафике не меньше 10 запросов"
